// FOR ALL GET REQUESTS
export const GET_ORGANIZATION_INITIALIZE = "GET_ORGANIZATION_INITIALIZE";
export const GET_LOAN_SUMMARY = "GET_LOAN_SUMMARY";
export const GET_CUSTOMER_ELIGIBLE_AMOUNT = "GET_CUSTOMER_ELIGIBLE_AMOUNT";
export const GET_CUSTOMER_LOANS = "GET_CUSTOMER_LOANS";
export const GET_REPAYMENT_SCHEDULE = "GET_REPAYMENT_SCHEDULE";
// FOR ALL GET REQUESTS

// FOR ALL POST REQUESTS
export const REGISTER_CUSTOMER = "REGISTER_CUSTOMER";
export const SAVE_CUSTOMER_CONSENT = "SAVE_CUSTOMER_CONSENT";
export const GET_LOAN_OPTIONS = "GET_LOAN_OPTIONS";
export const ACCEPT_LOAN_TERMS = "ACCEPT_LOAN_TERMS";
export const SEND_OTP = "SEND_OTP";
export const VERIFY_OTP = "VERIFY_OTP";
// FOR ALL POST REQUESTS
